import { Injectable, Logger } from '@nestjs/common';
import { ConversationHistoryRepository } from './repositories/conversation-history.repository';

export type TextConversationPart = {
  kind: 'text';
  text: string;
};

export type ImageConversationPart = {
  kind: 'image';
  mimeType: string;
  data: string; // base64 encoded data
};

export type ConversationPart = TextConversationPart | ImageConversationPart;

export type ConversationTurn = {
  role: 'user' | 'model';
  parts: ConversationPart[];
};

export interface ConversationHistoryStore {
  load(conversationId: string): Promise<ConversationTurn[]>;
  append(conversationId: string, turns: ConversationTurn[]): Promise<void>;
}

export type LlmGenerateCommand = {
  prompt: string;
  conversationId?: string;
};

export type LlmGenerateResult = {
  answer: string;
  turns: ConversationTurn[];
};

@Injectable()
export class LlmService {
  private readonly logger = new Logger(LlmService.name);

  constructor(private readonly historyStore: ConversationHistoryRepository) {}

  async generate(command: LlmGenerateCommand): Promise<LlmGenerateResult> {
    this.logger.log(
      `Processing LLM generate command=${JSON.stringify(command)}`,
    );

    let history: ConversationTurn[] = [];

    if (command.conversationId) {
      history = await this.historyStore.load(command.conversationId);
      this.logger.log(
        `Loaded conversation history conversationId="${command.conversationId}" turns=${JSON.stringify(
          history,
        )}`,
      );
    } else {
      this.logger.log('No conversationId provided; skipping history lookup.');
    }

    const answer = 'This is a placeholder response generated by the service.';
    const newTurns: ConversationTurn[] = [
      {
        role: 'user',
        parts: [{ kind: 'text', text: command.prompt }],
      },
      {
        role: 'model',
        parts: [{ kind: 'text', text: answer }],
      },
    ];

    if (command.conversationId) {
      await this.historyStore.append(command.conversationId, newTurns);
      this.logger.log(
        `Appended demo turns to conversationId="${command.conversationId}" turns=${JSON.stringify(
          newTurns,
        )}`,
      );
    } else {
      this.logger.log(
        'Skipping history append because conversationId is missing.',
      );
    }

    return {
      answer,
      turns: command.conversationId ? [...history, ...newTurns] : newTurns,
    };
  }
}
