import { Injectable, Logger } from '@nestjs/common';

export type LlmGenerateCommand = {
  prompt: string;
  conversationId: string;
};

export type LlmGenerateResult = {
  answer: string;
};

@Injectable()
export class LlmService {
  private readonly logger = new Logger(LlmService.name);

  generate(command: LlmGenerateCommand): LlmGenerateResult {
    this.logger.log(
      `Processing LLM generate command=${command.prompt} for conversationId=${command.conversationId}`,
    );

    return {
      answer: 'This is a placeholder response generated by the service.',
    };
  }
}
